name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Dashboard code
      uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: pnpm
    - name: Install package and build
      run: |
        pnpm install
        pnpm build
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: aa
        path: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

